### ISSUE TITLE
Suggestion for device_class

### ISSUE THREAD

**Issue by nsleigh** [Option-Zero/esphome-components#2]
First off, thanks for this code, helped me get my "ESP32-C6: ePulse Feather" battery monitor working.

For the battery voltage I suggest using this conifg to stop it showing up as a battery:
```
    battery_voltage:
      name: Battery voltage
      id: batt_v
      device_class: voltage
      state_class: measurement
```

For the rate setting I couldn't really find a suitable class so did this:
```
    rate:
      name: Battery discharge rate
      id: batt_discharge_rate
      device_class: ""
      state_class: measurement
```

(I needed this to stop my low battery template finding these two entities and reporting them as low batteries.)
